# Generated by Django 5.2.6 on 2025-09-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('numberOfPersons', models.IntegerField()),
                ('estimatedCost', models.FloatField()),
                ('food', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('budgetType', models.CharField(max_length=50)),
                ('budgetAmount', models.IntegerField(blank=True, null=True)),
                ('emergencyContact', models.CharField(max_length=20)),
                ('companionContact', models.CharField(blank=True, max_length=20, null=True)),
                ('submittedAt', models.DateTimeField()),
            ],
        ),
    ]
